### ISSUE TITLE
`shadow-runner` doesn't work in minimal setup

### ISSUE THREAD

**Issue by wildwestrom** [lambdaisland/kaocha-cljs2#12]
# `shadow-runner` doesn't work in minimal setup

### Expected:
Tests run without problems.

### Actual:
```log
shadow-cljs - config: /Users/main/Code/clojure/kaocha-cljs2/shadow-cljs.edn
shadow-cljs - starting via "clojure"
[:test] Compiling ...
========= Running Tests =======================
SHADOW import error /Users/main/Code/clojure/kaocha-cljs2/.shadow-cljs/builds/test/dev/out/cljs-runtime/lambdaisland.chui.remote.js

/Users/main/Code/clojure/kaocha-cljs2/.shadow-cljs/builds/test/dev/out/cljs-runtime/lambdaisland/glogi.cljs:87
  (some-> (logger name) (.setLevel (level lvl))))
                        ^
TypeError: G__19978.setLevel is not a function
    at Object.lambdaisland$glogi$set_level [as set_level] (/Users/main/Code/clojure/kaocha-cljs2/.shadow-cljs/builds/test/dev/out/cljs-runtime/lambdaisland/glogi.cljs:87:25)
    at Object.lambdaisland$glogi$set_levels [as set_levels] (/Users/main/Code/clojure/kaocha-cljs2/.shadow-cljs/builds/test/dev/out/cljs-runtime/lambdaisland/glogi.cljs:92:3)
    at /Users/main/Code/clojure/kaocha-cljs2/.shadow-cljs/builds/test/dev/out/cljs-runtime/lambdaisland/chui/remote.cljs:23:1
    at global.SHADOW_IMPORT (/Users/main/Code/clojure/kaocha-cljs2/out/node-tests.js:64:44)
    at /Users/main/Code/clojure/kaocha-cljs2/out/node-tests.js:1681:1
    at Object.<anonymous> (/Users/main/Code/clojure/kaocha-cljs2/out/node-tests.js:1688:3)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
===============================================
[:test] Build completed. (164 files, 2 compiled, 0 warnings, 3.05s)
```

## Steps to reproduce

1. Create a minimal shadow-cljs project.
```shell
git clone https://github.com/wildwestrom/kaocha2-shadow-test.git && cd kaocha2-shadow-test
```
2. Install dependencies
```shell
yarn install
```
3. Run the `:test` build
```shell
shadow-cljs compile test
```

**Comment by plexus** [comment]
Can you make sure you are using the latest Glögi and try again?

**Comment by humorless** [comment]
Hi @wildwestrom , 

Is this issue already solved? I tried to clone the repo https://github.com/wildwestrom/kaocha2-shadow-test.git, but I can not find it anymore.

**Comment by wildwestrom** [comment]
Sorry, must've killed the repo while cleaning up. I don't have time to work on this unfortunately.

**Comment by humorless** [comment]
Hi @wildwestrom, 

I will close this issue for now, but I welcome you to raise it again if it still exists and you have the time.
